Project Plan for 4.32
eclipse-platform/www.eclipse.org-eclipse pull request #146
Opened 2024-04-04 12:14 UTC by elsazac

Project Plan for 4.32 release

2024-04-04 12:15 UTC, elsazac commented
@lshanmug Can you review this?

2024-04-05 08:07 UTC, lshanmug approved these changes

2024-04-05 08:08 UTC, lshanmug requested changes

2024-04-05 08:08 UTC, lshanmug commented on development/plans/eclipse_project_plan_4_32.xml
> +  of the Eclipse SDK after 4.31, designated release 4.32 and code-named 2024-03.
Should be 2024-06

2024-04-05 08:25 UTC, elsazac commented on development/plans/eclipse_project_plan_4_32.xml
> +  of the Eclipse SDK after 4.31, designated release 4.32 and code-named 2024-03.
done.

2024-04-05 08:28 UTC, lshanmug approved these changes

2024-04-05 08:29 UTC, merged