Find/Replace overlay: New/Noteworthy Entry
eclipse-platform/www.eclipse.org-eclipse pull request #184
Opened 2024-06-17 13:14 UTC by Wittmaxi

N&N for https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192

2024-06-17 21:49 UTC, HannesWell commented
Thanks for providing this.

> I am not sure yet how I can correctly render this page and I am not quite sure how to word the N&N. If you could give me a few hints and/or review my text, i'd be very thankful :)

Sure. :) In general you have already found the right place and after a coarse view it looks good already.

The Contributing Guide leads you to more detailed instructions and recommendations about the content and how to validate it:
https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/0ef3497d054caaed1d4e335192ce0c563088db76/CONTRIBUTING.md

You can try it out by simply opening the modified html file in your browser. It does not look exactly as deployed to the website (I think the theming is missing), but it should give you a good general impression.

Once this is submitted it will be published at https://eclipse.dev/eclipse/news/4.33/platform.php shortly later.

When you think this is ready I can have a detailed review.

2024-06-18 07:33 UTC, fedejeanne requested changes
Thank you for contributing this!
I just made some corrections based on the [instructions](https://eclipse.dev/eclipse/news/instructions.html).

Could you please also:
* Rename the files to use "-" instead of "_"
* Remove the "noise" (parts from buttons and texts in the background) from the edges of the screenshots

?

2024-06-18 07:33 UTC, fedejeanne commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_bottom.png" alt="Find/Replace overlay"/></p>
```suggestion
		<p><img src="images/overlay_bottom.png" alt=""/></p>
```

2024-06-18 07:33 UTC, fedejeanne commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_top_replace_closed.png" alt="Find/Replace overlay"/></p>
```suggestion
		<p><img src="images/overlay_top_replace_closed.png" alt=""/></p>
```

2024-06-18 07:33 UTC, fedejeanne commented on news/4.33/platform.html
> +			<img style="max-width: 600px;" src="images/overlay_top_replace_open.png" alt="Find/Replace overlay"/>
```suggestion
			<img src="images/overlay_top_replace_open.png" alt=""/>
```

2024-06-18 07:33 UTC, fedejeanne commented on news/4.33/platform.html
> +				<li><img style="max-width: 32px;" src="images/search_in_area.svg"/> Search in a selected area (Ctrl + shift + A)</li>
```suggestion
				<li><img src="images/case_sensitive.svg"/> Case sensitive search (<code>Ctrl</code> + <code>shift</code> + <code>C</code> in Windows)</li>
				<li><img src="images/whole_word.svg"/> Whole word search (<code>Ctrl</code> + <code>shift </code>+ <code>W</code> in Windows)</li>
				<li><imgsrc="images/regex.svg"/> Search for a regular expression (<code>Ctrl</code> + <code>shift</code> + <code>P</code> in Windows)</li>
				<li><img src="images/search_in_area.svg"/> Search in a selected area (<code>Ctrl</code> + <code>shift</code> + <code>A</code> in Windows)</li>
```

2024-06-18 07:33 UTC, fedejeanne commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_top_replace_open.png" alt="Find/Replace overlay"/></p>
```suggestion
		<p><img src="images/overlay_top_replace_open.png" alt=""/></p>
```

2024-06-22 11:01 UTC, Wittmaxi commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_top_replace_open.png" alt="Find/Replace overlay"/></p>
https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/1a45b4636439d41d6d0ac95249a239328a397ff8

2024-06-22 11:01 UTC, Wittmaxi commented on news/4.33/platform.html
> +				<li><img style="max-width: 32px;" src="images/search_in_area.svg"/> Search in a selected area (Ctrl + shift + A)</li>
https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/1a45b4636439d41d6d0ac95249a239328a397ff8

2024-06-22 11:01 UTC, Wittmaxi commented on news/4.33/platform.html
> +			<img style="max-width: 600px;" src="images/overlay_top_replace_open.png" alt="Find/Replace overlay"/>
https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/1a45b4636439d41d6d0ac95249a239328a397ff8

2024-06-22 11:01 UTC, Wittmaxi commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_top_replace_closed.png" alt="Find/Replace overlay"/></p>
https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/1a45b4636439d41d6d0ac95249a239328a397ff8

2024-06-22 11:01 UTC, Wittmaxi commented on news/4.33/platform.html
> +		<p><img style="max-width: 600px;" src="images/overlay_bottom.png" alt="Find/Replace overlay"/></p>
https://github.com/eclipse-platform/www.eclipse.org-eclipse/commit/1a45b4636439d41d6d0ac95249a239328a397ff8

2024-07-01 07:36 UTC, fedejeanne requested changes
![image](https://github.com/eclipse-platform/www.eclipse.org-eclipse/assets/2205684/79ece36c-7557-4460-8953-1c40b2642b37)

Also, I would rather have the screenshots in the "default" theme as opposed to the "dark" theme in order to be consistent across the document (see screenshots from previous feature).

2024-07-01 12:33 UTC, Wittmaxi commented
@fedejeanne @HeikoKlare I have updated the PR according to your suggestions. I have anticipated the merge of the Find/Replace History and already documented it in this PR

2024-07-01 12:33 UTC, Wittmaxi commented
![grafik](https://github.com/eclipse-platform/www.eclipse.org-eclipse/assets/16443184/13a460dc-d5dc-4e81-beb0-6839bdacc553)

2024-07-04 06:50 UTC, fedejeanne commented
> @fedejeanne @HeikoKlare I have updated the PR according to your suggestions. 

* You didn't provide an empty `alt` text for the images

Additionally
* The word `shift` needs to be properly capitalized (`Shift`)
* I would remove the screenshot showing the overlay at the bottom and simply mention the fact that you can have at the bottom **before** the previous screenshot since that one already shows the option right below "_Use find/replace overlay_" anyway.

> I have anticipated the merge of the Find/Replace History and already documented it in this PR
👍

2024-08-06 19:03 UTC, HeikoKlare commented
To have this N&N in soon and make people aware of the new feature, I have improved the N&N proposal according to the review and recent changes to the look and feel.
In more detail:
- Updated all screenshots with the current look and feel and proper cropping at the borders of the according shells.
- Removed the screenshot showing an overlay at the bottom of an editor. The editor was not completely shown so the screenshot looked a bit misplaced.
- Added a screenshot showing the expanded replace bar for comparison with the collapsed version.
- Added alternative descriptions for images.
- Made the shortcut references OS independent by referring to both the Windows/Linux and MacOS versions.
- Slightly improved the text.

A preview can be seen here: https://htmlpreview.github.io/?https://github.com/Wittmaxi/www.eclipse.org-eclipse/blob/MW_NN_find_replace_overlay/news/4.33/platform.html

@fedejeanne could you please have another look?

2024-08-07 08:25 UTC, fedejeanne requested changes
Remove the file `.png`, it's not necessary.

The rest looks good.

2024-08-07 09:20 UTC, HeikoKlare commented
Removed the obsolete file in df372a9.

2024-08-07 09:50 UTC, merged